name: performance-release

on:
  pull_request:
    paths:
    # Performance Distribute folder
    - 'FirebasePerformance/Distribute/**'

jobs:

  # Build release binary and upload artifact.
  release:
    if: github.repository == 'FirebasePrivate/firebase-ios-sdk'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode version
#      uses: maxim-lobanov/setup-xcode@1.0
#      with:
#        xcode-version: 11.3 # Set the Xcode version to the minimally supported Firebase version.
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Run build_zip.sh to build binary
      run: scripts/third_party/travis/retry.sh scripts/build.sh Performance all release
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: FirebasePerformance/Distribute/output/*
